#!/bin/bash
# {{AGENT_DISPLAY_NAME}} — Claude Code launcher with auto-recovery
# Generated by setup.sh. Edit modules/agent-script-linux.sh.tpl to change.

SESSION="{{AGENT_NAME}}"
WORKDIR="{{DEPLOYMENT_WORKSPACE}}"
CLAUDE_CMD="CLAUDE_CONFIG_DIR=$HOME/.claude-personal TELEGRAM_STATE_DIR=$HOME/.claude-personal/channels/telegram-{{AGENT_NAME}} claude --channels plugin:telegram@claude-plugins-official"

export PATH="$HOME/.nvm/versions/node/v24.14.1/bin:$HOME/.local/bin:$HOME/.bun/bin:/usr/local/bin:/usr/bin:/bin"
export CLAUDE_CONFIG_DIR="$HOME/.claude-personal"
export TELEGRAM_STATE_DIR="$HOME/.claude-personal/channels/telegram-{{AGENT_NAME}}"

CRASH_COUNT=0
CRASH_WINDOW_START=$(date +%s)
MAX_CRASHES=5
WINDOW_SECONDS=300

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }

claude_is_running() {
  tmux has-session -t "$SESSION" 2>/dev/null || return 1
  local pane_pid
  pane_pid=$(tmux list-panes -t "$SESSION" -F '#{pane_pid}' 2>/dev/null)
  [ -z "$pane_pid" ] && return 1
  pgrep -P "$pane_pid" -f "claude" >/dev/null 2>&1
}

start_session() {
  tmux kill-session -t "$SESSION" 2>/dev/null
  sleep 1
  tmux new-session -d -s "$SESSION" -c "$WORKDIR" "$CLAUDE_CMD" || { log "ERROR: tmux new-session failed"; return 1; }
  sleep 2
  tmux has-session -t "$SESSION" 2>/dev/null || { log "ERROR: session did not stay active"; return 1; }
  log "Session $SESSION started OK"
}

check_backoff() {
  local now=$(date +%s)
  local elapsed=$(( now - CRASH_WINDOW_START ))
  [ $elapsed -gt $WINDOW_SECONDS ] && { CRASH_COUNT=0; CRASH_WINDOW_START=$now; }
  CRASH_COUNT=$(( CRASH_COUNT + 1 ))
  if [ $CRASH_COUNT -ge $MAX_CRASHES ]; then
    log "WARN: $CRASH_COUNT crashes in ${elapsed}s — backoff 60s"
    sleep 60
    CRASH_COUNT=0
    CRASH_WINDOW_START=$(date +%s)
  fi
}

if claude_is_running; then
  log "$SESSION already running"
  exit 0
fi
tmux has-session -t "$SESSION" 2>/dev/null && log "Zombie session detected, recreating..."

start_session || exit 1

while true; do
  sleep 10
  if ! tmux has-session -t "$SESSION" 2>/dev/null; then
    log "tmux session dead, recreating..."
    check_backoff
    start_session || { log "ERROR: failed to recreate, retrying in 30s"; sleep 30; }
    continue
  fi
  if ! claude_is_running; then
    log "Claude died in tmux, recreating session..."
    check_backoff
    start_session || { log "ERROR: failed to recreate, retrying in 30s"; sleep 30; }
  fi
done
