# .env — secrets for {{AGENT_DISPLAY_NAME}}
# Generated by setup.sh. NEVER commit this file.

{{#if NOTIFICATIONS_CHANNEL_IS_TELEGRAM}}
# Telegram notifications
NOTIFY_BOT_TOKEN=
NOTIFY_CHAT_ID=
{{/if}}

{{#each MCPS_ATLASSIAN}}
# Atlassian workspace: {{name}}
ATLASSIAN_{{NAME_UPPER}}_TOKEN=
{{/each}}

{{#if MCPS_GITHUB_ENABLED}}
# GitHub MCP
GITHUB_PAT=
{{/if}}
