#!/bin/bash
# In-container first-run wizard. Collects secrets the host wizard refused to
# touch (Telegram bot token, GitHub PAT), writes them to /workspace/.env with
# mode 0600, and exits so `unless-stopped` restarts the container into its
# steady state.
set -euo pipefail

ENV_FILE="/workspace/.env"

echo ""
echo "╭──────────────────────────────────────────────╮"
echo "│ First-run setup for your dockerized agent    │"
echo "│ (values are written to /workspace/.env 0600) │"
echo "╰──────────────────────────────────────────────╯"
echo ""

# Telegram — required for the agent to be reachable.
# The official `telegram@claude-plugins-official` plugin handles pairing
# dynamically (no pre-configured chat id needed — the allowlist is built
# via /telegram:access pair <code> after first DM), so we only collect the
# bot token here. The allowlist lives in /home/agent/.claude/channels/
# (named volume) after pairing.
BOT=$(gum input --password --prompt "Telegram bot token (from @BotFather): ")
if [ -z "$BOT" ]; then
  echo "ERROR: Telegram bot token cannot be empty." >&2
  exit 1
fi

# GitHub PAT — optional. Gum returns empty on skip.
if gum confirm "Add a GitHub Personal Access Token (for gh / MCP)?" --default=no; then
  GH_PAT=$(gum input --password --prompt "GitHub PAT: ")
else
  GH_PAT=""
fi

umask 077
{
  echo "# Generated by docker/scripts/wizard-container.sh on $(date '+%Y-%m-%d %H:%M:%S')"
  echo "# NEVER commit this file."
  echo
  echo "TELEGRAM_BOT_TOKEN=${BOT}"
  [ -n "$GH_PAT" ] && echo "GITHUB_PAT=${GH_PAT}"
} > "$ENV_FILE"
chmod 0600 "$ENV_FILE"

echo ""
echo "✓ /workspace/.env written. Exiting — Docker will restart into steady state."
exit 0
